# Generated by Django 5.0.5 on 2024-05-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PostBooks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=50, null=True, verbose_name="Напишите название книги"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="images/", verbose_name="Загрузите фото"
                    ),
                ),
                ("description", models.TextField(verbose_name="Краткое описание")),
                (
                    "audio",
                    models.FileField(
                        blank=True,
                        upload_to="audio/",
                        verbose_name="Загрузите аудио файл",
                    ),
                ),
                (
                    "category_books",
                    models.CharField(
                        choices=[
                            ("Художественная литература", "Художественная литература"),
                            ("Информационная технология", "Информационная технология"),
                            ("Деловая литература", "Деловая литература"),
                            ("Юридическая литература", "Юридическая литература"),
                            ("Наука, образование", "Наука, образование"),
                            (
                                "Языкознание, иностранные языки",
                                "Языкознание, иностранные языки",
                            ),
                            ("Школьные учебники", "Школьные учебники"),
                            ("Детская литература", "Детская литература"),
                            ("Медицина, спорт, здоровье", "Медицина, спорт, здоровье"),
                            ("Другое", "Другое"),
                        ],
                        max_length=100,
                        verbose_name="Выберите категорию",
                    ),
                ),
                (
                    "audio_time",
                    models.PositiveIntegerField(
                        verbose_name="Укажите длительность аудио книг"
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Укажите автора"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
