# Generated by Django 5.0.5 on 2024-05-14 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostBooks',
            new_name='Books',
        ),
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'книг', 'verbose_name_plural': 'список книг'},
        ),
    ]
